// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzcxdjyyftewpkxlboee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6Y3hkanl5ZnRld3BreGxib2VlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4OTQ2MTQsImV4cCI6MjA2MzQ3MDYxNH0.5yRlhfZpfAFiaR-wz4fSyoB_cSwnnnHaus73hBQGZaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);